// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARaZPjvHvuXZ3hW2Okqr63XWe2BZeKLxs',
    appId: '1:684936399424:web:ab8547371bf8416ae02da5',
    messagingSenderId: '684936399424',
    projectId: 'workerapp-63bc8',
    authDomain: 'workerapp-63bc8.firebaseapp.com',
    storageBucket: 'workerapp-63bc8.firebasestorage.app',
    measurementId: 'G-66GX5JB36F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCR6XuUwi5aoetQUdgy8A3lU-syQFgm7I',
    appId: '1:684936399424:android:96367f788de24bf7e02da5',
    messagingSenderId: '684936399424',
    projectId: 'workerapp-63bc8',
    storageBucket: 'workerapp-63bc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHITBoEh6XO224to73o53c6eon3aSu6Fg',
    appId: '1:684936399424:ios:b9846e445494fde5e02da5',
    messagingSenderId: '684936399424',
    projectId: 'workerapp-63bc8',
    storageBucket: 'workerapp-63bc8.firebasestorage.app',
    iosBundleId: 'com.example.serviceMarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHITBoEh6XO224to73o53c6eon3aSu6Fg',
    appId: '1:684936399424:ios:b9846e445494fde5e02da5',
    messagingSenderId: '684936399424',
    projectId: 'workerapp-63bc8',
    storageBucket: 'workerapp-63bc8.firebasestorage.app',
    iosBundleId: 'com.example.serviceMarketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARaZPjvHvuXZ3hW2Okqr63XWe2BZeKLxs',
    appId: '1:684936399424:web:e1cc2785c272ed26e02da5',
    messagingSenderId: '684936399424',
    projectId: 'workerapp-63bc8',
    authDomain: 'workerapp-63bc8.firebaseapp.com',
    storageBucket: 'workerapp-63bc8.firebasestorage.app',
    measurementId: 'G-TNV5PWE0JQ',
  );
}
